# Generated by Django 5.2.12 on 2026-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_test_management', 'Can access test management'), ('manage_test_items', 'Can manage test items')],
                'default_permissions': (),
            },
        ),
    ]
