# Generated by Django 5.2.17 on 2026-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_core_testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('zone', models.CharField(max_length=64)),
            ],
        ),
    ]
