"""Forms for the AccessToken Wagtail admin.

Kept as a plain :class:`django.forms.Form` rather than a ``ModelForm``:
the creation flow writes a ``digest`` (never a plaintext token) and
derives ``prefix``/``suffix`` from a raw string generated by the service.
There is no one-to-one mapping between form fields and model fields, so
binding to the model would be misleading.
"""

from __future__ import annotations

from django import forms
from django.utils.translation import gettext_lazy as _


class AccessTokenCreateForm(forms.Form):
    """Fields a human fills in when issuing a new AccessToken.

    ``scopes`` is a comma-separated text field for now — a proper multi-
    select will land when the scope vocabulary is formalized. An empty
    value resolves to ``['*']`` at the service layer.
    """

    name = forms.CharField(
        label=_("Name"),
        max_length=100,
        help_text=_("A short label so you can recognize this token later."),
    )
    description = forms.CharField(
        label=_("Description"),
        required=False,
        widget=forms.Textarea(attrs={"rows": 3}),
        help_text=_("Optional. What will this token be used for?"),
    )
    scopes = forms.CharField(
        label=_("Scopes"),
        required=False,
        help_text=_(
            "Comma-separated list of scopes. Leave empty for full access ('*')."
        ),
    )
    expires_at = forms.DateTimeField(
        label=_("Expires at"),
        required=False,
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        help_text=_("Optional. Leave empty for a non-expiring token."),
    )

    def clean_scopes(self) -> list[str]:
        raw = self.cleaned_data.get("scopes", "") or ""
        scopes = [s.strip() for s in raw.split(",") if s.strip()]
        return scopes or ["*"]
