# Generated by Django 5.2.13 on 2026-05-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_media', '0003_reset_sequences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoxtailRendition',
            new_name='PhoxtailImageRendition',
        ),
    ]
