# Generated by Django 5.2.13 on 2026-06-20 16:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phoxtail_cms', '0001_initial'),
        ('phoxtail_design', '0001_initial'),
        ('phoxtail_media', '0001_initial'),
        ('wagtailcore', '0097_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Browser favicon for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon_dark',
            field=models.ForeignKey(blank=True, help_text='Browser favicon for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Favicon (Dark)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='font',
            field=models.ForeignKey(blank=True, help_text='Select a font for the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_design.fontfamily'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Site logo for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_admin',
            field=models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Logo'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_admin_dark',
            field=models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Logo (Dark)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_dark',
            field=models.ForeignKey(blank=True, help_text='Site logo for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Logo (Dark)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in light mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='og_image_dark',
            field=models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in dark mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Open Graph Image (Dark)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='symbol_admin',
            field=models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Symbol'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='symbol_admin_dark',
            field=models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Symbol (Dark)'),
        ),
        migrations.AddField(
            model_name='sitesettingfont',
            name='config',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='phoxtail_cms.sitesetting'),
        ),
        migrations.AddField(
            model_name='sitesettingfont',
            name='font_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='phoxtail_design.fontfamily'),
        ),
        migrations.AddField(
            model_name='sitesettingfont',
            name='role',
            field=models.ForeignKey(help_text='Semantic role this font serves (e.g., heading, body).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phoxtail_design.fontrole'),
        ),
        migrations.AddField(
            model_name='sitesettingpalette',
            name='config',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='phoxtail_cms.sitesetting'),
        ),
        migrations.AddField(
            model_name='sitesettingpalette',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='phoxtail_design.palette'),
        ),
        migrations.AddField(
            model_name='sitesettingpalette',
            name='role',
            field=models.ForeignKey(help_text='Semantic role this palette serves (e.g., surface, primary, accent).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phoxtail_design.paletterole'),
        ),
        migrations.AddConstraint(
            model_name='sitesettingfont',
            constraint=models.UniqueConstraint(fields=('config', 'role'), name='unique_sitesetting_font_role'),
        ),
        migrations.AddConstraint(
            model_name='sitesettingpalette',
            constraint=models.UniqueConstraint(fields=('config', 'role'), name='unique_sitesetting_role'),
        ),
    ]
