# Generated by Django 5.2.13 on 2026-05-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_cms', '0001_initial'),
        ('phoxtail_media', '0002_copy_from_wagtail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Browser favicon for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon_dark',
            field=models.ForeignKey(blank=True, help_text='Browser favicon for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Favicon (Dark)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Site logo for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_admin',
            field=models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Logo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_admin_dark',
            field=models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Logo (Dark)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_dark',
            field=models.ForeignKey(blank=True, help_text='Site logo for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Logo (Dark)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in light mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Open Graph Image'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image_dark',
            field=models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in dark mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Open Graph Image (Dark)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='symbol_admin',
            field=models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Symbol'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='symbol_admin_dark',
            field=models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage', verbose_name='Admin Symbol (Dark)'),
        ),
    ]
