# Generated by Django 5.2.12 on 2026-04-01 00:00

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import modelsearch.index
import phoxtail.core.mixins
import phoxtail.streams.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Author's role or position, e.g."
                            " 'Software Engineer' or 'Editor'."
                        ),
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short biography of the author.",
                        verbose_name="Bio",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Author",
                "verbose_name_plural": "Blog Authors",
            },
            bases=(
                models.Model,
                phoxtail.core.mixins.AdminURLMixin,
                modelsearch.index.Indexed,
            ),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    phoxtail.streams.fields.SchemaStreamField(
                        [], blank=True, block_lookup={}, null=True
                    ),
                ),
                (
                    "posts_per_page",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="How many blog posts to display per page",
                    ),
                ),
                (
                    "is_locked_for_references",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If checked, links to this page will appear"
                            " disabled on the website and won't redirect."
                        ),
                        verbose_name="Lock References",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blog",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    phoxtail.streams.fields.SchemaStreamField(
                        [], blank=True, block_lookup={}, null=True
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Brief introduction or summary of the post",
                        null=True,
                    ),
                ),
                (
                    "read_mins",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated reading time in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Reading time must be at least 1 minute"
                            )
                        ],
                        verbose_name="Reading Time",
                    ),
                ),
                (
                    "is_locked_for_references",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If checked, links to this page will appear"
                            " disabled on the website and won't redirect."
                        ),
                        verbose_name="Lock References",
                    ),
                ),
                (
                    "first_published_at_override",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Overrides the system-managed first published"
                            " date. Use when the original publication date"
                            " differs from when the page was first created"
                            " in the CMS."
                        ),
                        null=True,
                        verbose_name="Published Date Override",
                    ),
                ),
                (
                    "last_published_at_override",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Overrides the system-managed last published"
                            " date. Set only for significant updates — not"
                            " minor corrections."
                        ),
                        null=True,
                        verbose_name="Updated Date Override",
                    ),
                ),
                (
                    "hide_dates",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If checked, no publication or update dates will"
                            " be shown on this post."
                        ),
                        verbose_name="Hide Dates",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="The author of this post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="phoxtail_blog.blogauthor",
                    ),
                ),
                (
                    "preview_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Featured image for this post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="BlogPostPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="phoxtail_blog.blogpostpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Tags for categorizing blog posts",
                through="phoxtail_blog.BlogPostPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
