# Generated by Django 5.2.15 on 2026-06-20 17:13

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import phoxtail.core.mixins
import phoxtail.streams.fields
import phoxtail.streams.utils
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('phoxtail_media', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCategory',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Block Category',
                'verbose_name_plural': 'Block Categories',
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='StreamsAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Streams',
                'verbose_name_plural': 'Streams',
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VariantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Collection name (e.g., 'Material Design', 'Minimalist')", max_length=255, unique=True)),
                ('identifier', models.CharField(help_text="Unique identifier (e.g., 'material_design_3')", max_length=100, unique=True)),
                ('description', models.TextField(help_text="Short description of this collection's purpose")),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Display name', max_length=255, unique=True)),
                ('identifier', models.CharField(help_text="Unique identifier (e.g., 'header_section', 'simple_hero')", max_length=100, unique=True)),
                ('description', models.TextField(help_text="Description of this block's purpose and use case")),
                ('icon', models.CharField(blank=True, default='', help_text="Wagtail icon name for this block (e.g., 'image', 'doc-full', 'media'). Displayed in the block chooser.", max_length=100)),
                ('group', models.CharField(blank=True, default='', help_text="Group label shown in the block chooser (e.g., 'Blog', 'Media'). Leave empty for no grouping.", max_length=100)),
                ('is_shared', models.BooleanField(default=False, help_text="If checked, this block's content is defined once per site/locale (in Shared Blocks) and shared across pages. In page editors, only the variant chooser will be shown.")),
                ('source_app', models.CharField(blank=True, default='', help_text="Django app label that owns this block (e.g. 'phoxtail_blog'). Set automatically by populate_streams. Blank means no app dependency — the block is available in any project.", max_length=100)),
                ('schema', wagtail.fields.StreamField([('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 63), ('list_field', 65), ('list_struct', 67), ('stream', 71)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Field name (e.g., 'title', 'subtitle'). Use lowercase with underscores.", 'max_length': 100}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Is this field required?', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Help text shown to content editors', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Wagtail icon name (e.g., 'image', 'doc-full', 'media'). Can use default Wagtail icons or custom SVG icons.", 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum character length (optional)', 'min_value': 0, 'required': False}), 5: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum character length (optional)', 'min_value': 1, 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Index this field content for searching', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_length', 4), ('max_length', 5), ('search_index', 6)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of visible text lines (optional)', 'min_value': 1, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_length', 4), ('max_length', 5), ('rows', 8), ('search_index', 6)]], {}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3)]], {}), 11: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_length', 4), ('max_length', 5)]], {}), 12: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum value (optional)', 'required': False}), 13: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum value (optional)', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_value', 12), ('max_value', 13)]], {}), 15: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Total number of digits (optional)', 'min_value': 1, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of decimal places (optional)', 'min_value': 0, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_value', 12), ('max_value', 13), ('max_digits', 15), ('decimal_places', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Date format (from Django's DATE_INPUT_FORMATS, optional)", 'max_length': 50, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('format', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': "Time format (from Django's TIME_INPUT_FORMATS, optional)", 'max_length': 50, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('format', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': "DateTime format (from Django's DATETIME_INPUT_FORMATS, optional)", 'max_length': 50, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('format', 22)]], {}), 24: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum character length (text-only, optional)', 'min_value': 0, 'required': False}), 25: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum character length (text-only, optional)', 'min_value': 1, 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Rich text editor selection (optional)', 'max_length': 100, 'required': False}), 27: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('ol', 'Ordered List'), ('ul', 'Unordered List'), ('link', 'Link'), ('document-link', 'Document Link'), ('blockquote', 'Block Quote'), ('superscript', 'Superscript'), ('subscript', 'Subscript'), ('code', 'Code'), ('hr', 'Horizontal Rule'), ('embed', 'Embed'), ('image', 'Image')], 'help_text': 'Select which formatting features should be available in the editor', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_length', 24), ('max_length', 25), ('search_index', 6), ('editor', 26), ('features', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'Regular expression pattern to validate against', 'max_length': 500}), 30: ('wagtail.blocks.TextBlock', (), {'help_text': 'Error messages in JSON format (optional)\\n{"required": "This field is required", "invalid": "Invalid format"}', 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('regex', 29), ('min_length', 4), ('max_length', 5), ('error_messages', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'The value stored when this choice is selected', 'label': 'Value'}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text shown to the user', 'label': 'Label'}), 34: ('wagtail.blocks.StructBlock', [[('value', 32), ('label', 33)]], {'label': 'Choice'}), 35: ('wagtail.blocks.ListBlock', (34,), {'help_text': 'Add one entry per available choice'}), 36: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('choices', 35), ('search_index', 6)]], {}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Restrict to specific page types (optional)\\nExample: blog.BlogPage or app.HomePage', 'max_length': 255, 'required': False}), 38: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Allow selection of page tree root', 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('page_type', 37), ('can_choose_root', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'help_text': 'Target snippet model in format: app_label.ModelName\nExample: blog.Author or products.Category', 'max_length': 255}), 41: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('target_model', 40)]], {}), 42: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum URL length (optional)', 'min_value': 0, 'required': False}), 43: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum URL length (optional)', 'min_value': 1, 'required': False}), 44: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum embed width in pixels (optional)', 'min_value': 1, 'required': False}), 45: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum embed height in pixels (optional)', 'min_value': 1, 'required': False}), 46: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('min_length', 42), ('max_length', 43), ('max_width', 44), ('max_height', 45)]], {}), 47: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46)]], {'help_text': 'Fields in this structure (innermost layer, no further nesting)', 'min_num': 1}), 48: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Start with this structure collapsed in the editor', 'required': False}), 49: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 47), ('collapsed', 48)]], {}), 50: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 49)]], {'help_text': 'Fields and structures (can nest one more layer)', 'min_num': 1}), 51: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 50), ('collapsed', 48)]], {}), 52: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 49)]], {'help_text': 'Blocks in this stream (can contain L2 structures)', 'min_num': 1}), 53: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number of blocks required (optional)', 'min_value': 0, 'required': False}), 54: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of blocks allowed (optional)', 'min_value': 1, 'required': False}), 55: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Start with all blocks collapsed in the editor', 'required': False}), 56: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 52), ('min_num', 53), ('max_num', 54), ('collapsed', 55)]], {}), 57: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 49)]], {'help_text': 'Fields in each list item (can contain L2 structures)', 'min_num': 1}), 58: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number of items required (optional)', 'min_value': 0, 'required': False}), 59: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of items allowed (optional)', 'min_value': 1, 'required': False}), 60: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Start with all list items collapsed in the editor', 'required': False}), 61: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 57), ('min_num', 58), ('max_num', 59), ('collapsed', 60)]], {}), 62: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 51), ('stream', 56), ('list_struct', 61)]], {'help_text': 'Blocks that compose this structure (supports nested structures)', 'min_num': 1}), 63: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 62), ('collapsed', 48)]], {}), 64: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46)]], {'help_text': 'Define the field type and configuration for each item in this list (add exactly one)', 'max_num': 1, 'min_num': 1}), 65: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 64), ('min_num', 58), ('max_num', 59), ('collapsed', 60)]], {}), 66: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 51), ('stream', 56), ('list_struct', 61)]], {'help_text': 'Blocks that define the structure of each list item (supports nested structures)', 'min_num': 1}), 67: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 66), ('min_num', 58), ('max_num', 59), ('collapsed', 60)]], {}), 68: ('wagtail.blocks.StreamBlock', [[('char_field', 7), ('text_field', 9), ('email_field', 10), ('url_field', 11), ('blockquote_field', 11), ('raw_html_field', 11), ('integer_field', 14), ('float_field', 14), ('decimal_field', 17), ('boolean_field', 10), ('date_field', 19), ('time_field', 21), ('datetime_field', 23), ('rich_text_field', 28), ('regex_field', 31), ('choice_field', 36), ('multiple_choice_field', 36), ('page_chooser_field', 39), ('document_chooser_field', 10), ('image_chooser_field', 10), ('image_field', 10), ('snippet_chooser_field', 41), ('video_chooser_field', 10), ('audio_chooser_field', 10), ('embed_field', 46), ('struct', 63), ('list_field', 65), ('list_struct', 67)]], {'help_text': 'Blocks that can be used in this stream. Editors can add any of these in any order.', 'min_num': 1}), 69: ('wagtail.blocks.TextBlock', (), {'help_text': 'Per-block-type limits in JSON format (optional)\nExample:\n{\n  "image_chooser_field": {"min_num": 1, "max_num": 5},\n  "embed_field": {"max_num": 2}\n}', 'required': False}), 70: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Include this stream content in search indexing', 'required': False}), 71: ('wagtail.blocks.StructBlock', [[('name', 0), ('required', 1), ('help_text', 2), ('icon', 3), ('blocks', 68), ('min_num', 53), ('max_num', 54), ('block_counts', 69), ('collapsed', 55), ('search_index', 70)]], {})}, help_text='Define the structure of this block using field schema blocks, nested structures, lists, and streams')),
                ('page_types', models.ManyToManyField(blank=True, help_text='Restrict this block to specific page types. Leave empty to make it available on all pages.', limit_choices_to=phoxtail.streams.utils._page_content_type_choices, related_name='+', to='contenttypes.contenttype', verbose_name='Page Types')),
                ('categories', models.ManyToManyField(blank=True, help_text='Broad purpose groupings (e.g. Marketing, Ecommerce). Keep the vocabulary small and governed.', related_name='blocks', to='phoxtail_streams.blockcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SharedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', phoxtail.streams.fields.SchemaStreamField([], blank=True, block_lookup={}, null=True)),
                ('block', models.ForeignKey(help_text='The shared block this content belongs to.', limit_choices_to={'is_shared': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shared_blocks', to='phoxtail_streams.block')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_blocks', to='wagtailcore.locale')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_blocks', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Shared Block',
                'verbose_name_plural': 'Shared Blocks',
                'constraints': [models.UniqueConstraint(fields=('block', 'site', 'locale'), name='unique_shared_block')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='BlockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant name for identification (e.g., 'Centered', 'With Background')", max_length=255)),
                ('identifier', models.CharField(help_text="Identifier for this variant (e.g., 'centered_dark', 'split_layout')", max_length=100)),
                ('description', models.TextField(help_text='Design rationale and approach. Explain why this variant exists and what makes it different.')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default variant for its block. Only one default per block.')),
                ('html', models.TextField(default='', help_text='HTML template with DTL/Jinja2 tags.')),
                ('css', models.TextField(blank=True, default='', help_text='CSS styles for this variant.')),
                ('javascript', models.TextField(blank=True, default='', help_text='JavaScript code for this variant.')),
                ('block', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='phoxtail_streams.block')),
                ('preview_image_desktop', models.ForeignKey(blank=True, help_text='Desktop (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('preview_image_desktop_dark', models.ForeignKey(blank=True, help_text='Desktop (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('preview_image_mobile', models.ForeignKey(blank=True, help_text='Mobile (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('preview_image_mobile_dark', models.ForeignKey(blank=True, help_text='Mobile (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('preview_image_tablet', models.ForeignKey(blank=True, help_text='Tablet (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('preview_image_tablet_dark', models.ForeignKey(blank=True, help_text='Tablet (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage')),
                ('collection', models.ForeignKey(blank=True, help_text="Optional design-system label for this variant (e.g. 'Material Design 3').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='phoxtail_streams.variantcollection')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'ordering': ['block__name', 'collection__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('block', 'collection', 'identifier'), name='unique_block_collection_variant_identifier'), models.UniqueConstraint(condition=models.Q(('collection', None)), fields=('block', 'identifier'), name='unique_variant_identifier_per_block_no_collection'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('block',), name='unique_default_variant_per_block')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
