# Generated by Django 5.2.15 on 2026-08-31 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='render_in_preview',
            field=models.BooleanField(default=True, help_text='Whether the site-wide render includes this block in the Wagtail preview panel and Studio screenshots. Uncheck for analytics and tracking scripts.'),
        ),
        migrations.AddField(
            model_name='block',
            name='site_slot',
            field=models.CharField(blank=True, choices=[('head_start', 'Head start'), ('head_end', 'Head end'), ('body_start', 'Body start'), ('before_content', 'Before content'), ('after_content', 'After content'), ('body_end', 'Body end')], default='', help_text="Render this block automatically at this position on every page of a site that has filled in its shared content. A page that places the block itself takes over on that page. Requires 'is_shared'. Leave empty for normal per-page placement.", max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='slot_order',
            field=models.IntegerField(default=0, help_text='Render order among blocks pinned to the same slot (lower renders first).'),
        ),
        migrations.AddField(
            model_name='sharedblock',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Variant used when this block renders site-wide (and the fallback for per-page placements that don't choose one). Leave empty to use the block's default variant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_blocks', to='phoxtail_streams.blockvariant'),
        ),
    ]
