# Generated by Django 5.2.13 on 2026-05-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_media', '0002_copy_from_wagtail'),
        ('phoxtail_streams', '0003_alter_block_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvariant',
            name='preview_image',
            field=models.ForeignKey(blank=True, help_text='Optional preview screenshot of this variant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
    ]
