# Generated by Django 5.2.14 on 2026-05-28 22:29

import modelsearch.index
import phoxtail.core.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_streams', '0004_alter_blockvariant_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCategory',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Block Category',
                'verbose_name_plural': 'Block Categories',
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, models.Model, modelsearch.index.Indexed),
        ),
        migrations.AddField(
            model_name='block',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Broad purpose groupings (e.g. Marketing, Ecommerce). Keep the vocabulary small and governed.', related_name='blocks', to='phoxtail_streams.blockcategory', verbose_name='Categories'),
        ),
    ]
