# Generated by Django 5.2.13 on 2026-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_streams', '0006_block_source_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display label for this registry (e.g. 'Phoxtail Registry').", max_length=100)),
                ('base_url', models.URLField(help_text='Root URL of the registry, e.g. https://registry.phoxtail.com — no trailing slash.')),
                ('token', models.CharField(help_text='Read token issued by the registry. Never displayed after save.', max_length=200)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registries',
                'ordering': ['name'],
            },
        ),
    ]
