# Generated by Django 5.2.13 on 2026-06-17 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_media', '0005_phoxtaildocument_description'),
        ('phoxtail_streams', '0006_block_source_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamsAdminPermission',
        ),
        migrations.RemoveField(
            model_name='blockvariant',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_desktop',
            field=models.ForeignKey(blank=True, help_text='Desktop (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_desktop_dark',
            field=models.ForeignKey(blank=True, help_text='Desktop (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_mobile',
            field=models.ForeignKey(blank=True, help_text='Mobile (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_mobile_dark',
            field=models.ForeignKey(blank=True, help_text='Mobile (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_tablet',
            field=models.ForeignKey(blank=True, help_text='Tablet (light mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
        migrations.AddField(
            model_name='blockvariant',
            name='preview_image_tablet_dark',
            field=models.ForeignKey(blank=True, help_text='Tablet (dark mode) preview screenshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_media.phoxtailimage'),
        ),
    ]
