[project]
name = "{{ phoxtail_project_name }}"
image_prefix = "{{ phoxtail_project_name }}"

[db.clusters.cms]
apps = [
    "auth.Group",
    "users",
    "account",
    "allauth",
    "wagtailusers",
    "wagtailcore.Locale",
    "wagtailcore.Collection",
    "wagtailcore.Revision",
    "wagtailcore.Page",
    "wagtailcore.PageViewRestriction",
    "wagtailcore.Site",
    "taggit",
    "wagtailimages.Image",
    "wagtaildocs.Document",
    "wagtailmedia.Media",
    "app",
]
