# Generated by Django 5.2.12 on 2026-03-21 20:33

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import phoxtail.streams.fields
import uuid
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phoxtail_design', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', phoxtail.streams.fields.SchemaStreamField([], blank=True, block_lookup={}, null=True)),
                ('is_locked_for_references', models.BooleanField(default=False, help_text="If checked, links to this page will appear disabled on the website and won't redirect.", verbose_name='Lock References')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ForeignKey(blank=True, help_text='Browser favicon for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('favicon_dark', models.ForeignKey(blank=True, help_text='Browser favicon for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon (Dark)')),
                ('font', models.ForeignKey(blank=True, help_text='Select a font for the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_design.fontfamily')),
                ('logo', models.ForeignKey(blank=True, help_text='Site logo for light mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('logo_admin', models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Logo')),
                ('logo_admin_dark', models.ForeignKey(blank=True, help_text='Used as the main logo in the admin interface (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Logo (Dark)')),
                ('logo_dark', models.ForeignKey(blank=True, help_text='Site logo for dark mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo (Dark)')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in light mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open Graph Image')),
                ('og_image_dark', models.ForeignKey(blank=True, help_text='Image displayed when sharing on social media in dark mode. Recommended size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Open Graph Image (Dark)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('symbol_admin', models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (light mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Symbol')),
                ('symbol_admin_dark', models.ForeignKey(blank=True, help_text='Displayed as the small icon in admin areas like the sidebar (dark mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Admin Symbol (Dark)')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the schedule item', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the schedule item', max_length=150, null=True)),
                ('color', wagtail_color_panel.fields.ColorField(blank=True, help_text='The color of the schedule item', max_length=7, null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfigFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('config', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='app.siteconfig')),
                ('font_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='phoxtail_design.fontfamily')),
                ('role', models.ForeignKey(help_text='Semantic role this font serves (e.g., heading, body).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phoxtail_design.fontrole')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('config', 'role'), name='unique_siteconfig_font_role')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfigPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('config', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='app.siteconfig')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='phoxtail_design.palette')),
                ('role', models.ForeignKey(help_text='Semantic role this palette serves (e.g., surface, primary, accent).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='phoxtail_design.paletterole')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('config', 'role'), name='unique_siteconfig_role')],
            },
        ),
    ]
