# Generated by Django 5.2.15 on 2026-06-20 17:13

import django.db.models.deletion
import modelsearch.index
import phoxtail.core.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agent',
                'permissions': [('access_chatbot', 'Can access the AI chatbot')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_history', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='InferenceProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('model_prefix', models.CharField(blank=True, max_length=64)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_env_var', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AgentSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
    ]
