# Generated by Django 5.2.15 on 2026-06-20 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('phoxtail_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='phoxtail_agent.inferenceprovider'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_artifact_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_agent.modelartifact'),
        ),
        migrations.AddField(
            model_name='agentsitesetting',
            name='default_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phoxtail_agent.modelartifact'),
        ),
        migrations.AlterUniqueTogether(
            name='modelartifact',
            unique_together={('provider', 'identifier')},
        ),
    ]
