# Generated by Django 5.2.13 on 2026-05-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_agent', '0002_conversation_message_history_drop_message_toolcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
