# Generated by Django 5.2.15 on 2026-07-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentsitesetting',
            options={'verbose_name': 'Inference'},
        ),
    ]
