# Generated by Django 5.2.13 on 2026-04-18 20:13

import django.db.models.deletion
import phoxtail.core.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokensAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Access Tokens',
                'verbose_name_plural': 'Access Tokens',
                'permissions': [('access_tokens_management', 'Can access Access Tokens management'), ('create_access_tokens', 'Can create Access Tokens'), ('revoke_access_tokens', 'Can revoke Access Tokens'), ('manage_all_tokens', 'Can view and revoke tokens across all users')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('token_type', models.CharField(choices=[('personal', 'Personal')], default='personal', max_length=20)),
                ('prefix', models.CharField(max_length=8)),
                ('suffix', models.CharField(max_length=4)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='phoxtail_to_user_id_96c464_idx')],
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, models.Model),
        ),
    ]
