# Generated by Django 5.2.15 on 2026-06-20 17:13

import modelsearch.index
import phoxtail.core.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('token_type', models.CharField(choices=[('personal', 'Personal')], default='personal', max_length=20)),
                ('prefix', models.CharField(max_length=8)),
                ('suffix', models.CharField(max_length=4)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AccessTokensAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'API Tokens',
                'verbose_name_plural': 'API Tokens',
                'permissions': [('access_tokens_management', 'Can access API Tokens management'), ('create_access_tokens', 'Can create API Tokens'), ('revoke_access_tokens', 'Can revoke API Tokens'), ('manage_all_tokens', 'Can view and revoke tokens across all users')],
                'default_permissions': (),
            },
        ),
    ]
