# Generated by Django 5.2.17 on 2026-09-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_tokens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='unrestricted',
            field=models.BooleanField(default=False, help_text='Let this token do anything its owner can do, including capabilities added to this site in future. Convenient for your own machine; too broad for anything you hand to a service or connect from a phone. Leave off and choose scopes instead.'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='scopes',
            field=models.JSONField(default=list, help_text='The permissions this token may use, as codenames such as phoxtail_streams.change_blockvariant. Scopes only ever narrow: a token can never do something its owner cannot. Required unless the token is unrestricted.'),
        ),
    ]
