# Generated by Django 5.2.17 on 2026-09-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_tokens', '0003_accesstoken_unrestricted_alter_accesstoken_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('chatbot', 'Chatbot')], default='personal', max_length=20),
        ),
    ]
