services:
  web:
{% if not registry_mode %}
    build:
      target: {{ environment }}
      ssh:
        - default
{% endif %}
    image: {{ image_name }}
    pull_policy: {% if registry_mode %}always{% else %}build{% endif %}

    restart: always
    user: {% if registry_mode %}"1000:1000"{% else %}"${HOST_UID:-1000}:${HOST_GID:-1000}"{% endif %}

    volumes:
{% if not registry_mode %}
      - .:/app
{% endif %}
      - ${HOME}/.phoxtail:/home/app/.phoxtail:ro
{% if registry_mode %}
      - static_files:/app/static
      - media_files:/app/media
{% endif %}
    env_file:
      - ./.env
{% if environment == "development" %}
    ports:
      - "80:80"
{% endif %}
    depends_on:
      - db

  db:
    image: postgres:{{ postgres_version }}
    restart: always
    env_file:
      - ./.env
{% if environment == "development" %}
    ports:
      - "5432:5432"
{% endif %}
    volumes:
      - postgres_data:{{ pg_data_path }}
      - ./db-backups:/db-backups

{% if environment == "development" %}
  docs:
    build:
      target: {{ environment }}
      ssh:
        - default
    image: {{ image_name }}
    pull_policy: build
    profiles: ["docs"]
    working_dir: /app/docs
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "mkdocs serve --dev-addr 0.0.0.0:8000"

{% elif environment == "production" %}
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
{% if registry_mode %}
      - static_files:/usr/share/nginx/html/static:ro
      - media_files:/usr/share/nginx/html/media:ro
{% else %}
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
{% endif %}
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    profiles: ["ssl"]
    env_file:
      - ./.env
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
{% if registry_mode %}
      - static_files:/usr/share/nginx/html/static:ro
      - media_files:/usr/share/nginx/html/media:ro
{% else %}
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
{% endif %}
    depends_on:
      - nginx

{% endif %}
volumes:
  postgres_data:
{% if environment == "production" %}
  certbot_conf:
  certbot_www:
{% if registry_mode %}
  static_files:
  media_files:
{% endif %}
{% endif %}
