"""Chat-block rendering: the chatbot answers through the streams block system.

Architecture:

- **Discovery** — one ``find_blocks(query)`` tool searches the Block library
  (Wagtail search over name/identifier/description; ``Block.description`` is
  the human- and agent-facing "when to use me" text) and returns the top
  candidates *with their value JSON schemas inline*, generated by walking
  ``Block.schema`` — the same stored schema the Wagtail factory consumes.
- **Lane A** — ``render_block(identifier, value)`` deserializes and renders any
  discovered block through the existing streams pipeline
  (``to_python`` -> ``clean`` -> ``render``), no page involved, and streams the
  HTML to the chat pane as a ``block_html`` SSE event.
- **Lane B** — ``design_block(html, css, javascript)`` lets the agent
  invent a component on the spot. It renders inline like any block, following
  the variant-author conventions (self-scoped CSS under a unique root class,
  design tokens via CSS custom properties). Promotion to a real
  Block/BlockVariant goes through the existing studio MCP tools.

Rendered payloads are stashed out-of-band and popped by the chat stream
handler; only a small confirmation JSON travels back into the model's
context window.

BEFORE PRODUCTION — three trust decisions are deliberately deferred while the
chatbot is development-only (authenticated CMS staff, dev projects). Decide
them before the first client deployment enables the chatbot:

1. Write-tool safety: content the agent reads can steer it into mutating
   tools. The durable answer is human-in-the-loop approval on writes. Note
   that stripping write tools alone cannot enforce a readonly mode:
   design_block's JavaScript executes in the browser with the chat
   user's session and could perform writes through the HTTP API.
2. Rich text / raw HTML: LLM output landing in a ``rich_text_field`` renders
   through ``|richtext`` unsanitized — a live XSS surface. Needs sanitization
   or a curated chat-eligible flag on Block.
3. Chooser lookups: chooser fields fetch DB objects by PK inside
   ``to_python``. Today the chat endpoint's auth gate is the only check; if
   the API ever grows per-object read rules, the render path needs them too.
"""

from __future__ import annotations

import json
import logging
import re
import uuid
from types import SimpleNamespace
from typing import TYPE_CHECKING, Any

from asgiref.sync import sync_to_async

if TYPE_CHECKING:
    from pydantic_ai import RunContext, Tool, ToolDefinition


def _import_pydantic_ai() -> None:
    """Bind pydantic_ai names into module globals on first use.

    Deferred because this module loads at django.setup() via the chat router,
    and pydantic_ai costs ~50MB RSS per process. The names must land in
    globals (not function locals) because Tool() resolves the tool functions'
    string annotations (e.g. ``RunContext[None]``) against this module's
    namespace via get_type_hints().
    """
    global RunContext, Tool, ToolDefinition
    from pydantic_ai import RunContext, Tool, ToolDefinition


logger = logging.getLogger(__name__)

# Tool names whose results carry a chat_block_id the SSE layer must resolve.
CHAT_BLOCK_TOOLS = {"render_block", "design_block"}

# Payloads keyed by chat_block_id, popped exactly once by the chat stream
# handler. Kept out of the tool result on purpose: returning rendered HTML
# would feed it back into the model's context window.
# Each entry: {"kind": "block_html"|"block_custom", ...payload}
_pending: dict[str, dict[str, Any]] = {}

_FIND_BLOCKS_LIMIT = 5

# ---------------------------------------------------------------------------
# Block.schema -> LLM-facing JSON schema
# ---------------------------------------------------------------------------

_SCALAR_FIELD_SCHEMAS: dict[str, dict[str, Any]] = {
    "char_field": {"type": "string"},
    "text_field": {"type": "string"},
    "email_field": {"type": "string", "format": "email"},
    "url_field": {"type": "string", "format": "uri"},
    "blockquote_field": {"type": "string"},
    "raw_html_field": {"type": "string", "description": "Raw HTML"},
    "integer_field": {"type": "integer"},
    "float_field": {"type": "number"},
    "decimal_field": {"type": "number"},
    "boolean_field": {"type": "boolean"},
    "date_field": {"type": "string", "format": "date"},
    "time_field": {"type": "string", "format": "time"},
    "datetime_field": {"type": "string", "format": "date-time"},
    "rich_text_field": {"type": "string", "description": "Rich text as HTML"},
    "regex_field": {"type": "string"},
    "embed_field": {"type": "string", "format": "uri", "description": "Embeddable media URL"},
}

_CHOOSER_FIELD_TARGETS: dict[str, str] = {
    "page_chooser_field": "Page",
    "document_chooser_field": "Document",
    "image_chooser_field": "Image",
    "image_field": "Image",
    "snippet_chooser_field": "snippet",
    "video_chooser_field": "video Media",
    "audio_chooser_field": "audio Media",
}


def _field_json_schema(block_type: str, cfg: Any) -> dict[str, Any] | None:
    """Map one Block.schema item to a JSON-schema fragment for tool calling."""

    def get(key: str, default: Any = None) -> Any:
        try:
            return cfg.get(key, default)
        except AttributeError:
            return default

    schema: dict[str, Any] | None = None

    if block_type in _SCALAR_FIELD_SCHEMAS:
        schema = dict(_SCALAR_FIELD_SCHEMAS[block_type])
        if get("max_length"):
            schema["maxLength"] = get("max_length")
        if get("min_value") is not None:
            schema["minimum"] = get("min_value")
        if get("max_value") is not None:
            schema["maximum"] = get("max_value")
        if block_type == "regex_field" and get("regex"):
            schema["pattern"] = get("regex")

    elif block_type in ("choice_field", "multiple_choice_field"):
        choices = [str(c.get("value")) for c in (get("choices") or []) if c.get("value")]
        labels = ", ".join(f"{c.get('value')} ({c.get('label')})" for c in (get("choices") or []) if c.get("value"))
        item = {"type": "string"}
        if choices:
            item["enum"] = choices
        if block_type == "multiple_choice_field":
            schema = {"type": "array", "items": item}
        else:
            schema = item
        if labels:
            schema["description"] = f"Choices: {labels}"

    elif block_type in _CHOOSER_FIELD_TARGETS:
        target = _CHOOSER_FIELD_TARGETS[block_type]
        if block_type == "snippet_chooser_field" and get("target_model"):
            target = f"{get('target_model')} snippet"
        schema = {
            "type": "integer",
            "description": (
                f"Database ID of an existing {target}. Discover valid IDs with the relevant list/search tools."
            ),
        }

    elif block_type == "list_field":
        inner_items = get("blocks") or []
        child_schema: dict[str, Any] = {"type": "string"}
        if inner_items:
            child = _field_json_schema(inner_items[0].block_type, inner_items[0].value)
            if child:
                child_schema = child
        schema = {"type": "array", "items": child_schema}

    elif block_type in ("struct", "list_struct"):
        properties: dict[str, Any] = {}
        required: list[str] = []
        for item in get("blocks") or []:
            name = item.value.get("name", "unnamed")
            child = _field_json_schema(item.block_type, item.value)
            if child is None:
                continue
            properties[name] = child
            if item.value.get("required", True):
                required.append(name)
        obj: dict[str, Any] = {"type": "object", "properties": properties}
        if required:
            obj["required"] = required
        schema = {"type": "array", "items": obj} if block_type == "list_struct" else obj

    elif block_type == "stream":
        allowed = [item.value.get("name", "unnamed") for item in (get("blocks") or [])]
        schema = {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {"type": "string", "enum": allowed} if allowed else {"type": "string"},
                    "value": {"type": "object"},
                },
                "required": ["type", "value"],
            },
            "description": f"Mixed content stream. Allowed types: {', '.join(allowed)}",
        }

    if schema is None:
        return None

    if block_type in ("list_field", "list_struct", "stream"):
        if get("min_num") is not None:
            schema["minItems"] = get("min_num")
        if get("max_num") is not None:
            schema["maxItems"] = get("max_num")

    help_text = get("help_text")
    if help_text:
        existing = schema.get("description")
        schema["description"] = f"{help_text} ({existing})" if existing else help_text

    return schema


def block_value_json_schema(block) -> dict[str, Any]:
    """Generate the JSON schema of a Block's ``value`` from its stored schema."""
    properties: dict[str, Any] = {}
    required: list[str] = []
    for item in block.schema:
        name = item.value.get("name", "unnamed")
        field_schema = _field_json_schema(item.block_type, item.value)
        if field_schema is None:
            continue
        properties[name] = field_schema
        if item.value.get("required", True):
            required.append(name)
    schema: dict[str, Any] = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return schema


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _strip_nulls(value: Any) -> Any:
    """Drop explicit nulls so optional fields fall back to block defaults.

    Models often send ``"value_prefix": null`` for omitted optionals;
    ``to_python`` passes None straight through and templates print "None".
    ``clean()`` normalizes this on the live path but not on replay/partials.
    """
    if isinstance(value, dict):
        return {k: _strip_nulls(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        return [_strip_nulls(v) for v in value if v is not None]
    return value


def render_chat_block(identifier: str, value: dict, dom_id: str, validate: bool = True) -> str:
    """Render a streams block from a plain value dict, with no page involved.

    ``to_python`` is the deserializer Wagtail runs when loading a StreamField;
    ``render`` is what render_block_fragment uses for pages. The only page
    residue is the ``block`` context variable that DB-authored variant
    templates read (``block.id`` / ``block.value``) — normally supplied by the
    page template's stream loop, here by a stand-in.
    """
    from phoxtail.streams.cache import get_cached_dynamic_blocks

    blocks = dict(get_cached_dynamic_blocks())
    if identifier not in blocks:
        available = ", ".join(sorted(blocks))
        raise KeyError(f"Unknown block '{identifier}'. Available: {available}")
    block_instance = blocks[identifier]
    value = _strip_nulls(value or {})
    typed_value = block_instance.to_python(value)
    # clean() both validates and normalizes (e.g. a missing optional char
    # field deserializes as None but cleans to ""). Replay and partial
    # renders still want the normalization — they just must not fail on it.
    try:
        typed_value = block_instance.clean(typed_value)
    except Exception:
        if validate:
            raise
    stand_in = SimpleNamespace(id=dom_id, value=typed_value)
    return str(block_instance.render(typed_value, context={"block": stand_in}))


def pop_pending(chat_block_id: str) -> dict[str, Any] | None:
    return _pending.pop(chat_block_id, None)


def render_history_tool_call(tool_name: str, args: dict) -> dict[str, Any] | None:
    """Re-render a stored chat-block tool call for conversation replay.

    Deterministic: the tool call's args in ``message_history`` are the full
    source of truth, exactly as page bodies re-render from stored JSON.
    Returns a message item dict, or None when re-rendering isn't possible
    (e.g. the block was deleted since).
    """
    try:
        if tool_name == "render_block":
            html = render_chat_block(
                args["identifier"],
                args.get("value") or {},
                f"chat-{uuid.uuid4().hex[:12]}",
                validate=False,
            )
            return {"role": "assistant", "type": "block_html", "html": html}
        if tool_name == "design_block":
            return {
                "role": "assistant",
                "type": "block_custom",
                "html": args.get("html") or "",
                "css": args.get("css") or "",
                "javascript": args.get("javascript") or "",
            }
    except Exception:
        logger.warning("Could not replay chat block tool call '%s'", tool_name, exc_info=True)
    return None


# ---------------------------------------------------------------------------
# Partial-JSON repair (speculative streaming re-render)
# ---------------------------------------------------------------------------


def try_parse_partial_json(fragment: str) -> dict | None:
    """Best-effort parse of a streaming, possibly-truncated JSON object.

    Closes open strings and brackets; drops dangling members. Returns None
    when no valid object can be recovered — callers simply skip that delta.
    """
    fragment = fragment.strip()
    if not fragment.startswith("{"):
        return None
    try:
        parsed = json.loads(fragment)
        return parsed if isinstance(parsed, dict) else None
    except json.JSONDecodeError:
        pass

    stack: list[str] = []
    in_str = False
    escaped = False
    for ch in fragment:
        if in_str:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch in "{[":
            stack.append(ch)
        elif ch in "}]" and stack:
            stack.pop()

    repaired = fragment + ('"' if in_str else "")
    closers = "".join("}" if opener == "{" else "]" for opener in reversed(stack))

    # A dangling key ("key" / "key": / trailing comma) makes the object
    # unclosable; peel trailing garbage until a candidate parses.
    for _ in range(6):
        candidate = repaired.rstrip()
        while candidate and candidate[-1] in ",:":
            candidate = candidate[:-1].rstrip()
        try:
            parsed = json.loads(candidate + closers)
            return parsed if isinstance(parsed, dict) else None
        except json.JSONDecodeError:
            # Drop what looks like a dangling key string and retry.
            if candidate.endswith('"'):
                cut = candidate.rfind('"', 0, len(candidate) - 1)
                if cut == -1:
                    return None
                repaired = candidate[:cut]
                continue
            return None
    return None


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

_FIND_BLOCKS_DESCRIPTION = (
    "Search the site's design-system block library for components that can "
    "render information visually inside this chat (charts, tables, cards, "
    "heroes, ...). Describe the SHAPE of the data you want to show (e.g. "
    "'breakdown of one amount into labeled parts', 'list of records with "
    "dates and amounts', 'single headline number'). Returns the best-matching "
    "blocks with their identifiers, when-to-use descriptions and the exact "
    "JSON schema their `value` must follow. ALWAYS prefer rendering "
    "structured answers with a block over describing data in prose: call "
    "this, pick a block, then call render_block."
)

_RENDER_BLOCK_DESCRIPTION = (
    "Render a design-system block directly inside the chat conversation, "
    "styled by the site's own templates. `identifier` and the shape of "
    "`value` come from a prior find_blocks call — `value` must follow that "
    "block's value_schema exactly. The block is shown to the user "
    "immediately; do not repeat its content in prose — at most add one "
    "short sentence of insight. On validation errors, fix `value` and retry."
)

_DESIGN_BLOCK_DESCRIPTION = (
    "Design and render a custom, one-off visual component directly inside "
    "the chat when no existing block fits (check find_blocks first). "
    "Provide HTML, plus optional CSS and JavaScript; it renders inline in "
    "the page, so follow the same conventions as block variants: wrap your "
    "HTML in one root element with a unique class you invent (e.g. "
    "'pxc-countdown-a7'), prefix EVERY CSS selector with that class, and "
    "scope your JavaScript to elements inside it. The site's design tokens "
    "are available as CSS custom properties (e.g. "
    "rgb(var(--color-primary-500, 99 102 241))) — use them with fallbacks "
    "so the component matches the site's brand in light and dark mode. "
    "Size content intrinsically (no 100vh or fixed widths): the component "
    "must adapt to its container's width, using @container phoxtail-block "
    "(...) rules for responsive breakpoints. If the user wants to keep the "
    "design, create a permanent Block and BlockVariant with the "
    "phoxtail_studio_create_block / phoxtail_studio_create_variant tools."
)

_FIND_BLOCKS_PARAMETERS = {
    "type": "object",
    "properties": {
        "query": {
            "type": "string",
            "description": ("Data shape and intent to visualize, e.g. 'parts of a whole with labels and amounts'"),
        },
    },
    "required": ["query"],
}

_RENDER_BLOCK_PARAMETERS = {
    "type": "object",
    "properties": {
        "identifier": {
            "type": "string",
            "description": "Block identifier from find_blocks",
        },
        "value": {
            "type": "object",
            "description": "Block value following the value_schema returned by find_blocks",
        },
    },
    "required": ["identifier", "value"],
}

_DESIGN_BLOCK_PARAMETERS = {
    "type": "object",
    "properties": {
        "html": {"type": "string", "description": "Self-contained HTML body markup"},
        "css": {"type": "string", "description": "CSS for the component (prefix every selector with your root class)"},
        "javascript": {
            "type": "string",
            "description": "Optional JavaScript, runs after the HTML is inserted (scope it to your root element)",
        },
        "title": {"type": "string", "description": "Short name for this component"},
    },
    "required": ["html"],
}


_STOP_WORDS = frozenset("a an and are as at be by for from in into is it of on or that the this to with".split())


def _search_blocks(query: str):
    """Rank chat-eligible Block rows for a query via the Wagtail search backend.

    The Postgres backend ANDs all terms, so a natural-language shape query
    ("breakdown of one amount into labeled parts") matches nothing as-is.
    We search the full query first, then each significant token separately
    and rank by how many tokens hit — OR semantics with relevance ordering.
    Falls back to the whole library so the agent always sees its options.
    Retrieval is deliberately swappable behind the same tool contract
    (e.g. for a vector-search backend).
    """
    from wagtail.search.backends import get_search_backend

    from phoxtail.streams.cache import get_cached_dynamic_blocks
    from phoxtail.streams.models import Block

    renderable = set(dict(get_cached_dynamic_blocks()))
    base_qs = Block.objects.filter(is_shared=False)
    backend = get_search_backend()
    query = (query or "").strip()

    scores: dict[str, float] = {}
    by_id: dict[str, Any] = {}

    def tally(hits, weight: float) -> None:
        try:
            for rank, b in enumerate(hits):
                if b.identifier not in renderable:
                    continue
                by_id[b.identifier] = b
                scores[b.identifier] = scores.get(b.identifier, 0.0) + weight - rank * 0.01
        except Exception:
            logger.warning("Block search failed for %r", query, exc_info=True)

    if query:
        tally(backend.search(query, base_qs), weight=10.0)
        tally(backend.autocomplete(query, base_qs), weight=5.0)
        tokens = [t for t in re.findall(r"[a-z0-9]+", query.lower()) if len(t) > 2 and t not in _STOP_WORDS]
        for token in tokens[:10]:
            tally(backend.search(token, base_qs), weight=1.0)

    ranked = sorted(scores, key=lambda ident: -scores[ident])
    results = [by_id[ident] for ident in ranked]
    for b in base_qs.all():  # unmatched blocks trail the ranked ones
        if b.identifier in renderable and b.identifier not in scores:
            results.append(b)
    return results


def _find_blocks_sync(query: str) -> str:
    blocks = _search_blocks(query)
    top, rest = blocks[:_FIND_BLOCKS_LIMIT], blocks[_FIND_BLOCKS_LIMIT:]
    payload = {
        "blocks": [
            {
                "identifier": b.identifier,
                "name": b.name,
                "description": b.description,
                "value_schema": block_value_json_schema(b),
            }
            for b in top
        ],
        "other_available": [{"identifier": b.identifier, "name": b.name} for b in rest],
    }
    if not payload["blocks"]:
        payload["note"] = "No blocks in the library match. Consider design_block for a custom one-off component."
    return json.dumps(payload)


async def _find_blocks(ctx: RunContext[None], query: str) -> str:
    try:
        return await sync_to_async(_find_blocks_sync)(query)
    except Exception as exc:
        logger.warning("find_blocks failed", exc_info=True)
        return json.dumps({"error": str(exc)})


async def _render_block(ctx: RunContext[None], identifier: str, value: dict) -> str:
    from django.core.exceptions import ValidationError

    dom_id = f"chat-{uuid.uuid4().hex[:12]}"
    try:
        html = await sync_to_async(render_chat_block)(identifier, value or {}, dom_id)
    except KeyError as exc:
        return json.dumps({"error": str(exc.args[0]) if exc.args else str(exc)})
    except ValidationError as exc:
        detail = getattr(exc, "message_dict", None) or getattr(exc, "messages", None) or str(exc)
        return json.dumps(
            {
                "error": "Block value failed validation. Fix the fields below and call render_block again.",
                "validation": detail if isinstance(detail, (dict, list)) else str(detail),
            },
            default=str,
        )
    except Exception as exc:
        logger.warning("render_block failed for '%s'", identifier, exc_info=True)
        return json.dumps({"error": f"Could not render block '{identifier}' ({exc}). Answer in plain text instead."})
    _pending[dom_id] = {"kind": "block_html", "html": html}
    return json.dumps(
        {
            "ok": True,
            "chat_block_id": dom_id,
            "note": ("The block is now visible to the user in the chat. Do not repeat its content in text."),
        }
    )


async def _design_block(
    ctx: RunContext[None],
    html: str,
    css: str = "",
    javascript: str = "",
    title: str = "",
) -> str:
    if not (html or "").strip():
        return json.dumps({"error": "html must not be empty."})
    dom_id = f"chat-{uuid.uuid4().hex[:12]}"
    _pending[dom_id] = {
        "kind": "block_custom",
        "html": html,
        "css": css or "",
        "javascript": javascript or "",
        "title": title or "",
    }
    return json.dumps(
        {
            "ok": True,
            "chat_block_id": dom_id,
            "note": (
                "The custom component is now visible to the user in the chat. "
                "Do not repeat its content in text. If the user asks to keep or "
                "reuse this design, create a permanent Block "
                "(phoxtail_studio_create_block) and BlockVariant "
                "(phoxtail_studio_create_variant) from it."
            ),
        }
    )


_find_blocks.__name__ = "find_blocks"
_render_block.__name__ = "render_block"
_design_block.__name__ = "design_block"


def _make_prepare(name: str, description: str, parameters: dict):
    async def prepare(ctx: RunContext[None], tool_def: ToolDefinition) -> ToolDefinition:
        return ToolDefinition(
            name=name,
            description=description,
            parameters_json_schema=parameters,
        )

    return prepare


def get_chat_block_tools() -> list[Tool]:
    _import_pydantic_ai()
    return [
        Tool(
            _find_blocks,
            name="find_blocks",
            description=_FIND_BLOCKS_DESCRIPTION,
            prepare=_make_prepare("find_blocks", _FIND_BLOCKS_DESCRIPTION, _FIND_BLOCKS_PARAMETERS),
        ),
        Tool(
            _render_block,
            name="render_block",
            description=_RENDER_BLOCK_DESCRIPTION,
            prepare=_make_prepare("render_block", _RENDER_BLOCK_DESCRIPTION, _RENDER_BLOCK_PARAMETERS),
        ),
        Tool(
            _design_block,
            name="design_block",
            description=_DESIGN_BLOCK_DESCRIPTION,
            prepare=_make_prepare("design_block", _DESIGN_BLOCK_DESCRIPTION, _DESIGN_BLOCK_PARAMETERS),
        ),
    ]
