# Generated by Django 5.2.15 on 2026-06-20 17:13

import modelsearch.index
import phoxtail.core.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Display text for this link (e.g. 'My Subscriptions')", max_length=255)),
                ('url_name', models.CharField(help_text="Django URL name (e.g. 'dashboard:index')", max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Internal Link',
                'verbose_name_plural': 'Internal Links',
                'ordering': ['label'],
            },
            bases=(models.Model, phoxtail.core.mixins.AdminURLMixin, modelsearch.index.Indexed),
        ),
    ]
