# Generated by Django 5.2.12 on 2026-04-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
