# Generated by Django 5.2.13 on 2026-06-20 16:42

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import uuid
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Font family name as it appears in CSS (e.g., 'Inter', 'Roboto')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the font and its intended use')),
                ('category', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans Serif'), ('monospace', 'Monospace'), ('display', 'Display'), ('handwriting', 'Handwriting')], default='sans-serif', help_text='Font category - helps with fallback selection and appropriate usage', max_length=50)),
                ('fallback', models.CharField(blank=True, default='system-ui, -apple-system, sans-serif', help_text="CSS fallback fonts (e.g., 'system-ui, -apple-system, sans-serif')", max_length=255)),
            ],
            options={
                'verbose_name': 'Font Family',
                'verbose_name_plural': 'Font Families',
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='FontRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Heading', 'Body', 'Monospace')", max_length=100, unique=True)),
                ('identifier', models.CharField(help_text="CSS namespace identifier (e.g., 'heading'). Used as prefix in CSS variables: --font-{identifier}", max_length=50, unique=True)),
                ('description', models.TextField(help_text='Describes the semantic purpose of this font role.')),
            ],
            options={
                'verbose_name': 'Font Role',
                'verbose_name_plural': 'Font Roles',
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PaletteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Surface', 'Primary', 'Accent')", max_length=100, unique=True)),
                ('identifier', models.CharField(help_text="CSS namespace identifier (e.g., 'surface'). Used as prefix in CSS variables: --color-{identifier}-{shade}", max_length=50, unique=True)),
                ('description', models.TextField(help_text='Describes the semantic purpose of this role and how its shades map to light/dark mode (e.g., shade-50 for light backgrounds, shade-950 for dark backgrounds).')),
            ],
            options={
                'verbose_name': 'Palette Role',
                'verbose_name_plural': 'Palette Roles',
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PaletteSet',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Tailwind', 'Spring')", max_length=100, unique=True)),
                ('identifier', models.CharField(help_text='Slug-style identifier matching the filesystem group directory', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text="Optional description of the palette set's purpose or theme")),
            ],
            options={
                'verbose_name': 'Palette Set',
                'verbose_name_plural': 'Palette Sets',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='FontWeight',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveIntegerField(default=400, help_text='Font weight value (100=Thin, 400=Regular, 700=Bold, 900=Black)')),
                ('style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', help_text='Font style', max_length=20)),
                ('file', models.FileField(help_text='WOFF2 font file (convert TTF/OTF to WOFF2 first)', upload_to='fonts/')),
                ('family', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='phoxtail_design.fontfamily')),
            ],
            options={
                'verbose_name': 'Font Weight',
                'verbose_name_plural': 'Font Weights',
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('family', 'weight', 'style'), name='unique_family_weight_style')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Name of the palette (e.g., 'red', 'custom_blue')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the palette')),
                ('shade_50', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 50 (lightest)', max_length=7)),
                ('shade_100', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 100', max_length=7)),
                ('shade_200', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 200', max_length=7)),
                ('shade_300', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 300', max_length=7)),
                ('shade_400', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 400', max_length=7)),
                ('shade_500', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 500 (base)', max_length=7)),
                ('shade_600', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 600', max_length=7)),
                ('shade_700', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 700', max_length=7)),
                ('shade_800', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 800', max_length=7)),
                ('shade_900', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 900', max_length=7)),
                ('shade_950', wagtail_color_panel.fields.ColorField(help_text='Hex color for shade 950 (darkest)', max_length=7)),
                ('palette_set', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='phoxtail_design.paletteset')),
            ],
            options={
                'verbose_name': 'Palette',
                'verbose_name_plural': 'Palettes',
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('palette_set', 'title'), name='unique_palette_set_title')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
