# Generated by Django 5.2.14 on 2026-05-12 17:33

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoxtail_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteSet',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Tailwind', 'Spring')", max_length=100, unique=True)),
                ('identifier', models.CharField(help_text='Slug-style identifier matching the filesystem group directory', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text="Optional description of the palette set's purpose or theme")),
            ],
            options={
                'verbose_name': 'Palette Set',
                'verbose_name_plural': 'Palette Sets',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='palette',
            name='title',
            field=models.CharField(help_text="Name of the palette (e.g., 'red', 'custom_blue')", max_length=100),
        ),
        migrations.AddField(
            model_name='palette',
            name='palette_set',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='phoxtail_design.paletteset'),
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.UniqueConstraint(fields=('palette_set', 'title'), name='unique_palette_set_title'),
        ),
    ]
