# Generated by Django 5.2.15 on 2026-09-06 00:34

import django.db.models.deletion
import modelsearch.index
import phoxtail.core.mixins
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', wagtail.fields.StreamField([('page', 3), ('internal_link', 5), ('external_link', 7), ('dropdown', 12), ('separator', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Entry text. Falls back to the target's own name when empty.", 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Open in new tab', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'The page this entry opens.', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('open_in_new_tab', 1), ('page', 2)]], {}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', ('phoxtail_core.InternalLink',), {'help_text': 'The route this entry opens.', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('open_in_new_tab', 1), ('link', 4)]], {}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'The address this entry opens.', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('label', 0), ('open_in_new_tab', 1), ('url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the group.', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading for the entries below.', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('page', 3), ('internal_link', 5), ('external_link', 7), ('separator', 10)]], {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('items', 11)]], {})}, help_text='The entries of this menu, in the order they are shown.', verbose_name='Items')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_menus', to='wagtailcore.locale', verbose_name='Locale')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_menus', to='wagtailcore.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Platform Menu',
                'verbose_name_plural': 'Platform Menus',
                'constraints': [models.UniqueConstraint(fields=('site', 'locale'), name='unique_dashboard_menu')],
            },
            bases=(phoxtail.core.mixins.AdminURLMixin, modelsearch.index.Indexed, models.Model),
        ),
    ]
